site_name: Open Model Interface
nav:
    - index.md
    - spec.md
    - rationale.md
theme:
    name: material
    palette:
        primary: orange
        accent: blue
    logo: images/omi-symbol.png
    favicon: images/omi-symbol.png
    features:
        - navigation.expand
markdown_extensions:
    - attr_list
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - admonition
repo_url: https://github.com/modzy/openmodelinterface
repo_name: modzy/openmodelinterface
edit_uri: edit/main/docs/
